server:
  port: 8080
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/books?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
#    url: jdbc:mysql://127.0.0.1:3306/books?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: mxy713
mybatis-plus:
  global-config:
    db-config:
      #逻辑删除全局字段名
      logic-delete-field: deleted
      #逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.maxiangyu.code.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
